INSERT INTO item (id, name) VALUES (1, 'item-1')
INSERT INTO item (id, name) VALUES (2, 'item-2')
INSERT INTO item (id, name) VALUES (3, 'item-3')
INSERT INTO item (id, name) VALUES (4, 'item-4')
INSERT INTO item (id, name) VALUES (5, 'item-5')